version: "3"
services:

  apachephp:
    build: php_apache
    container_name: apachephp_docker_symfony
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./php_apache/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    networks:
      - dev

  database:
    image: mysql:8.0
    container_name: db_docker_symfony
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_docker_symfony
    restart: always
    depends_on:
      - database
    ports:
      - "8081:80"
    environment:
      PMA_HOST: database
    networks:
      - dev

  maildev:
    image: maildev/maildev
    container_name: maildev_docker_symfony
    restart: always
    command: bin/maildev --web 80 --smtp 25 --hide-extensiosn STARTTLS
    ports:
      - "8082:80"
    networks:
      - dev





networks:
    dev:

volumes:
  db-data:
